# Generated by Django 2.2.1 on 2019-11-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_token', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounting',
            name='accounting_coupon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounting',
            name='accounting_discount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
