# Generated by Django 2.2.1 on 2019-09-26 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_token', '0003_auto_20190718_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_class', models.CharField(max_length=30)),
                ('accounting_data', models.IntegerField(default=0)),
                ('accounting_date', models.CharField(default='MMdd', max_length=30)),
                ('user_accounting_post_at', models.DateTimeField(auto_now_add=True, verbose_name='PostTime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者收藏',
                'verbose_name_plural': '使用者收藏',
            },
        ),
    ]
