# Generated by Django 2.2.1 on 2019-09-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_token', '0004_useraccounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounting',
            name='accounting_date',
            field=models.CharField(default='0926', max_length=30),
        ),
    ]
