# Generated by Django 2.2.1 on 2019-05-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('coupon_title', models.CharField(max_length=150)),
                ('coupon_class', models.CharField(max_length=20)),
                ('coupon_content', models.CharField(max_length=200)),
                ('coupon_create_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('coupon_create_at',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('user_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('user_create_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('user_create_at',),
            },
        ),
    ]
