# Generated by Django 2.2.1 on 2019-05-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_data', '0002_auto_20190523_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('coupon_create_at',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('user_create_at',)},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='id',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
