# Generated by Django 2.2.1 on 2019-05-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_data', '0003_auto_20190523_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
