# Generated by Django 2.2.1 on 2019-05-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MangerDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
    ]
