# Generated by Django 2.2.1 on 2019-05-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangerDB', '0002_remove_item_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(choices=[('差評', 'bad'), ('中等', 'normal'), ('好', 'good')], max_length=1)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
