# Generated by Django 2.2.1 on 2019-05-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangerDB', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
